---
apiVersion: v1
kind: Secret
metadata:
  name: longusername1234-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-atl/longusername1234-frontend-gitops
